source/API/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import QuoteViewSet, get_token_view

app_name = 'API'

router = DefaultRouter()
router.register('quote', QuoteViewSet, basename='quote')

urlpatterns = [
    path('get-token/', get_token_view, name='get_token'),
    path('', include(router.urls)),
]

source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView
app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset')
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('API/', include('API.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include
from .views import IndexView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index')
]

source/webapp/models.py
from django.db import models
from django.contrib.sessions.models import Session


STATUS_NEW = 'new'
STATUS_MODERATED = 'moderated'
STATUS_CHOICES = [
    (STATUS_MODERATED, 'Модерировано'),
    (STATUS_NEW, 'Новая'),
]

STATUS_DEFAULT = STATUS_NEW


class Quote(models.Model):
    text = models.TextField(max_length=2000, verbose_name='Текст')
    author = models.CharField(max_length=100, verbose_name='Автор')
    email = models.EmailField(verbose_name='Email')
    rating = models.IntegerField(verbose_name='Рейтинг', default=0)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, verbose_name='Статус',
                              default=STATUS_DEFAULT)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Цитата'
        verbose_name_plural = 'Цитаты'
        ordering = ['-created_at', ]

    @classmethod
    def get_moderated(cls):
        return cls.objects.filter(status=STATUS_MODERATED)

    def __str__(self):
        return f'{self.author}, {self.text[:20]}...'


class Vote(models.Model):
    session_key = models.CharField(max_length=40, verbose_name='Ключ сессии')
    rating = models.IntegerField(choices=((1, 'up'), (-1, 'down')), verbose_name='Рэйтинг')
    quote = models.ForeignKey('webapp.Quote', related_name='votes', verbose_name='Цитата',
                              on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.quote}: {self.rating}'

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинги'
        ordering = ['quote', 'rating']

source/webapp/views.py
from django.shortcuts import render

# Create your views here.

source/webapp/views/quote_views.py
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView

from webapp.models import Quote


class IndexView(ListView):
    template_name = 'quote/index.html'
    model = Quote
    queryset = Quote.objects.all()
    

source/webapp/templates/partial/article_list.html
{% if is_paginated %}
    {% include 'partial/pagination.html' %}
{% endif %}

<div class="row">
{% for project in projects %}
    <div class="col-12 col-sm-12 col-md-6 col-lg-4">
        <div class="card my-4" style="width: 18rem">
            <div class="card-body">
                <h3><a href="{% url "webapp:project_view" project.pk %}">{{ project.name }}</a></h3>
                <p>
                    <label for="selected_articles-{{ project.pk }}">Select:</label>
                    <input type="checkbox" name="selected_articles"
                           id="selected_articles-{{ project.pk }}" value="{{ project.pk }}">
                </p>
                <p>
                    {% for i in project.user.all %}
                        <a class="users" href="{% url 'accounts:detail' i.pk %}">{{ i.username }}</a>
                    {% endfor %}
                </p>
                {% if perms.webapp.change_project or project.user == request.user %}
                    <p><a href="{% url 'webapp:project_update' project.pk %}">Обновить</a></p>
                {% endif %}
                {% if perms.webapp.delete_project or project.user == request.user %}
                    <p><a href="{% url 'webapp:project_delete' project.pk %}">Удалить</a></p>
                {% endif %}
            </div>
        </div>
    </div>
{% empty %}
    <h2 class="text-center">Нет проектов</h2>
{% endfor %}
<div>

{% if is_paginated %}
     {% include 'partial/pagination.html' %}
{% endif %}

source/webapp/templates/partial/form.html
{% if not fields_only %}
    <form action="{{ action_url }}" method="{{ form_method }}" enctype="{{ enctype }}">
        {% csrf_token %}
{% endif %}
        {% for error in form.non_field_errors %}
            <p class="error">{{ error }}</p>
        {% endfor %}
        {% for field in form %}
            {% include 'partial/form_field.html' %}
        {% endfor %}

{% if not fields_only %}
        <br/>
        <input type="submit" value="{{ button_text|default:"Подтвердить" }}"/>
    </form>
{% endif %}

source/webapp/templates/partial/form_field.html
<label for="{{ field.id_for_label }}">{{ field.label }}</label><br/>
        {{ field }}<br/>
        {% for error in field.errors %}
            <p class="error"> {{ error }}</p>
        {% endfor %}

source/webapp/templates/partial/pagination.html
<div class="pagination">
    <span class="step-links">
        <a href="?page=1" class="btn btn-warning mt-1 ml-1">&laquo; В начало</a>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-warning mt-1 ml-1">{{ page_obj.previous_page_number }}</a>
        {% else %}
            <span class="btn btn-warning mt-1 ml-1">{{ page_obj.number }}</span>
        {% endif %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-warning mt-1 ml-1">{{ page_obj.next_page_number }}</a>
        {% else %}
            <span class="page-disabled btn btn-warning mt-1 ml-1">{{ page_obj.number }}</span>
        {% endif %}
        <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-warning mt-1 ml-1">В конец &raquo;</a>
    </span>
</div>